/*
 * This source file was generated by the Gradle 'init' task
 */
package bloque_1;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        int cont = 0;
        ArrayList<Thread> threads = new ArrayList<>();

        while (cont < 10) {
            Sensor sensor = new Sensor(cont);
            Thread thread = new Thread(new ManejarSensor(sensor));
            threads.add(thread);
            thread.start();
            cont++;
        }

        for (Thread t : threads) {
            try {
                t.join();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        System.out.println("Programa finalizado");
    }

    static class ManejarSensor implements Runnable {
        private final Sensor sensor;
        private int cont;

        public ManejarSensor(Sensor sensor) {
            this.sensor = sensor;
            this.cont = 0;
        }

        @Override
        public void run() {
            while (sensor.verificar()) {
                //System.out.println("El sensor " + sensor.getId() + " tiene temperatura  " + sensor.getTemp() + "°C");
                cont++;
                sensor.actualizarTemp();
            }
            
            System.out.println("El sensor " + sensor.getId() + " tiene temperatura  " + sensor.getTemp() + "°C - Se detiene el sensor a la " + cont + " iteración");
        }
    }
}
