/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class App {
    public static void main(String[] args) throws IOException {
        try {
            ServerSocket servidor = new ServerSocket(8080);

            while (true) {
                Socket cliente = servidor.accept();
                System.out.println("Cliente conectado: " + cliente.getInetAddress().getHostAddress());

                Thread thread = new Thread(new ManejarCliente(cliente));
                thread.start();
            }
        } catch (IOException e) {
            e.printStackTrace();  
        }
    }

    static class ManejarCliente implements Runnable {
        private Socket cliente;

        public ManejarCliente(Socket cliente) {
            this.cliente = cliente;
        }

        @Override
        public void run() {
            try {
                BufferedReader reader = new BufferedReader(new java.io.InputStreamReader(cliente.getInputStream()));
                PrintWriter writer = new PrintWriter(cliente.getOutputStream(), true);

                String mensaje;
                while ((mensaje = reader.readLine()) != null) { 
                    System.out.println("Mensaje recibido: " + mensaje);

                    if (mensaje.equalsIgnoreCase("salir")) {
                        writer.println("Conexión cerrada. ¡Adiós!");
                        break;
                    }
                    writer.println("Echo: " + procesarMensaje(mensaje));
                }
                cliente.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        private String procesarMensaje(String mensaje) {
            String newmensaje = "";

            for (int i = mensaje.length() - 1; i >= 0; i--) {
                newmensaje += (char) (mensaje.charAt(i));
            }
            return newmensaje;
        }
    }
}
