/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.ArrayList;

public class App {
    private static int favor = 0;
    private static int contra = 0;

    public static void main(String[] args) {
        ArrayList<Thread> threads = new ArrayList<>();

        for (int i = 0; i < 100; i++) {
            Thread t = new Thread(new Votante());
            threads.add(t);
            t.start();
        }

        for (Thread t : threads) {
            try {
                t.join();
            } catch (Exception e) {
            }
        }

        System.out.println("Votos a favor: " + favor);
        System.out.println("Votos en contra: " + contra);
        System.err.println("Total de votos: " + (favor + contra));
    }

    public static synchronized void votarAFavor() {
        favor++;
    }

    public static synchronized void votarEnContra() {
        contra++;
    }

    static class Votante implements Runnable {
        @Override
        public void run() {
            try {
                Thread.sleep((long) (Math.random() * 100));
            } catch (Exception e) {
            }
            if (Math.random() < 0.5) {
                votarAFavor();
            } else {
                votarEnContra();
            }
        }
    }
}
