/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        ArrayList<Thread> threads = new ArrayList<>();

        for (int i = 0; i < 3; i++) {
            Thread thread = new Thread(new ManejarAuto(i));
            threads.add(thread);
            thread.start();
        }
        
        for (Thread thread : threads) {
            try {
                thread.join();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

        System.out.println("¡Todos llegaron a la meta!");
    }

    static class ManejarAuto implements Runnable {
        private final Auto auto;
        private final int id;

        public ManejarAuto(int id) {
            this.auto = new Auto();
            this.id = id + 1;
        }

        @Override
        public void run() {
            while (!auto.llegoALaMeta()) {
                auto.avanzar();
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
            System.out.println("El auto "+ id + " llegó");
        }
    }
}
