/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class App {
    public static void main(String[] args) {
        try {   
            ServerSocket server = new ServerSocket(5000);

            while (true) {
                Socket cliente = server.accept();
                System.out.println("Cliente conectado");

                Thread thread = new Thread(new ManejarCliente(cliente));
                thread.start();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    static class ManejarCliente implements Runnable {
        private Socket cliente;

        public ManejarCliente(Socket cliente) {
            this.cliente = cliente;
        }

        @Override
        public void run() {
            try {
                BufferedReader file = new BufferedReader(new FileReader("src/main/resources/Archivo.txt"));
                BufferedReader reader = new BufferedReader(new InputStreamReader(cliente.getInputStream()));
                PrintWriter writer = new PrintWriter(cliente.getOutputStream(), true);

                String mensaje = reader.readLine();

                // Entiendo que esto podria hacerse mejor o a multiples archivos, pero por simplicidad lo dejo asi
                if (mensaje.equals("Archivo.txt")) {
                    String line;
                    while ((line = file.readLine()) != null) {
                        writer.println(line);
                    }
                } else {
                    System.out.println("Solicitud no reconocida: " + mensaje);
                }
                cliente.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
