/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    private static final Cuenta cuenta = new Cuenta(1000);
    public static void main(String[] args) {
        for (int i = 0; i < 2; i++) {
            // 1. Sin sincronización - 2. Con sincronización
            Thread thread = new Thread(new Rommie(2));
            thread.start();
        }
    }

    static class Rommie implements Runnable {
        private final int tipo;

        public Rommie(int tipo) {
            this.tipo = tipo;
        }

        @Override
        public void run() {
            for (int i = 0; i < 10; i++) {
                if (tipo == 1) {
                    cuenta.retirar(100);
                } else {
                    cuenta.retirarSync(100);
                }
            }
            System.out.println("Dinero restante: " + cuenta.getSaldo());
        }
    }
}
