/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        for (int i = 0; i < 3; i++) {
            Thread thread = new Thread(new ManejarRun());
            thread.run();
        }

        for (int i = 0; i < 3; i++) {
            Thread thread = new Thread(new ManejarStart());
            thread.start();
        }
    }

    static class ManejarRun implements Runnable {
        public ManejarRun() {
        }

        @Override
        public void run() {
            System.out.println("Ejecutando con run: " + Thread.currentThread().getName());
        }
    }

    static class ManejarStart implements Runnable {
        public ManejarStart() {
        }

        @Override
        public void run() {
            System.out.println("Ejecutando con start: " + Thread.currentThread().getName());
        }
    }
}
