/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class App {
    public static void main(String[] args) {
        try {
            ServerSocket server = new ServerSocket(5000);
            
            while (true) {
                Socket cliente = server.accept();
                System.out.println("Cliente conectado");

                Thread thread = new Thread(new ManejarCliente(cliente));
                thread.start();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    static class ManejarCliente implements Runnable {
        private Socket cliente;

        public ManejarCliente(Socket cliente) {
            this.cliente = cliente;
        }

        @Override
        public void run() {
            try {
                BufferedReader reader = new BufferedReader(new InputStreamReader(cliente.getInputStream()));
                PrintWriter writer = new PrintWriter(cliente.getOutputStream(), true);

                String mensaje = reader.readLine();

                if (mensaje != null) {
                    System.out.println("El cliente no envio mensaje");
                }
                String usuario = mensaje.split(":")[0];
                String password = mensaje.split(":")[1];
                // Aqui deberia ir la logica de validacion
                System.out.println("Usuario: " + usuario);
                System.out.println("Password: " + password);
                
                System.out.println("OK");
                cliente.close();
            } catch (SocketException | EOFException e) {
                System.err.println("Conexión perdida con el ciudadano (Red inestable).");
            } catch (Exception e) {
                System.out.println("ERROR");
                e.printStackTrace();
            }
        }
    }
}
