/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.ArrayList;

public class App {
    private static final Equipo grua = new Equipo("Grua");
    private static final Equipo escaner = new Equipo("Escaner");

    public static void main(String[] args) {
        ArrayList<Thread> trabajadores = new ArrayList<>();
        for (int i = 0; i < 2; i++) {
            Thread t = new Thread(new Trabajador(i));
            trabajadores.add(t);
            t.start();
        }

        for (Thread t : trabajadores) {
            try {
                t.join();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

        System.out.println("Todos los trabajadores han terminado.");

    }

    static class Trabajador implements Runnable {
        private final int id;

        public Trabajador(int id) {
            this.id = id;
        }

        /* Con deadlock
        @Override
        public void run() {
            if (id == 0) {
                synchronized (grua) {
                    grua.ocupar(id);
                    System.out.println("Trabajador " + id + " ha ocupado la grua.");
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    synchronized (escaner) {
                        escaner.ocupar(id);
                        System.out.println("Trabajador " + id + " ha ocupado el escaner.");
                    }
                }
            }
            else {
                synchronized (escaner) {
                    escaner.ocupar(id);
                    System.out.println("Trabajador " + id + " ha ocupado el escaner.");
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    synchronized (grua) {
                        grua.ocupar(id);
                        System.out.println("Trabajador " + id + " ha ocupado la grua.");
                    }
                }
           }
        }*/

        // Manejando una jerarquia de recursos para evitar el deadlock
        @Override
        public void run() {
            synchronized (grua) {
                grua.ocupar(id);
                System.out.println("Trabajador " + id + " ha ocupado la grua.");
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                synchronized (escaner) {
                    escaner.ocupar(id);
                    System.out.println("Trabajador " + id + " ha ocupado el escaner.");
                    escaner.liberar();
                }
                grua.liberar();
            }
        }
    }
}
